// Generated by scripts/generate_openapi_types.py from packages/api-contracts/openapi.yaml.
// Do not edit this file by hand; update OpenAPI and regenerate it.

export type MediaUploadReceipt = {
  status: "observed" | "applied" | "replayed";
  epoch: string;
  generation: number;
  mode: "paused" | "enabled";
  command_id: string;
  applied_at: string;
};

export type MediaUploadState = {
  target_ref: string;
  receipt: MediaUploadReceipt | null;
  last_success_at: string | null;
  updated_at: string;
  error_code: string | null;
  fresh: boolean;
};

export type MediaUploadCommand = {
  command_id: string;
  actor_id: string;
  mode: "paused" | "enabled";
  reason: string;
  status: "pending" | "running" | "uncertain" | "applied" | "rejected" | "superseded";
  created_at: string;
  expires_at: string;
  first_dispatched_at: string | null;
  completed_at: string | null;
  dispatch_count: number;
  error_code: string | null;
  receipt: MediaUploadReceipt | null;
  idempotent_replay: boolean;
};

export type MediaUploadOverview = {
  state: MediaUploadState | null;
  commands: Array<MediaUploadCommand>;
};

export type MediaUploadInput = {
  idempotency_key: string;
  target_ref: string;
  expected_epoch: string;
  expected_generation: number;
  expected_observed_at: string;
  mode: "paused" | "enabled";
  reason: string;
  confirmed: true;
};

export type MediaUploadResult = {
  command: MediaUploadCommand;
};

export type MediaUsageState = {
  config_digest: string;
  period_start: string;
  period_end: string;
  updated_at: string;
  last_success_at: string | null;
  last_until: string | null;
  class_a_highwater: string;
  class_b_highwater: string;
  review_required: boolean;
  review_reason: string | null;
  stop_recommended: boolean;
  last_status: "unknown" | "low_estimate" | "warning" | "high" | "stop_recommended";
  active_run: boolean;
  last_review_id: string | null;
  observation_fresh: boolean;
};

export type MediaUsageReview = {
  review_id: string;
  action: "acknowledge" | "rotate_period";
  status: "pending" | "applied" | "rejected";
  created_at: string;
  expires_at: string;
  completed_at: string | null;
  error_code: string | null;
  reason: string;
  next_period_start: string | null;
  next_period_end: string | null;
  idempotent_replay: boolean;
};

export type MediaUsageOverview = {
  state: MediaUsageState | null;
  reviews: Array<MediaUsageReview>;
  enforcement: "not_connected";
};

export type MediaUsageReviewInput = {
  idempotency_key: string;
  action: "acknowledge" | "rotate_period";
  expected_digest: string;
  expected_updated_at: string;
  next_period_start?: string | null;
  next_period_end?: string | null;
  reason: string;
  confirmed: true;
};

export type MediaUsageReviewResult = {
  review: MediaUsageReview;
  enforcement: "not_connected";
};

export type ApiError = {
  error: {
      code: string;
      message: string;
      request_id: string;
    };
};

export type HealthResponse = {
  status: "ok";
  service: string;
  version: string;
  time: string;
};

export type DependencyStatus = {
  name: string;
  status: "ok" | "unavailable" | "not_configured" | "schema_mismatch";
  detail?: string;
};

export type ReadinessResponse = {
  status: "ready" | "not_ready";
  service: string;
  version: string;
  dependencies: Array<DependencyStatus>;
  time: string;
};

export type HomeItem = {
  id: string;
  type: "work" | "performer" | "studio";
  code?: string;
  title: string;
  subtitle: string;
  href: string;
  image_url: string | null;
  image: ResponsiveImage | null;
};

export type HomeSection = {
  key: "discovery" | "latest" | "followed" | "performers" | "trending" | "most_viewed" | "editorial";
  title: string;
  items: Array<HomeItem>;
};

export type HomeResponse = {
  generated_at: string;
  sections: Array<HomeSection>;
};

export type SitemapEntry = {
  entity_type: "work" | "performer" | "studio";
  slug: string;
  updated_at: string;
};

export type SitemapResponse = {
  items: Array<SitemapEntry>;
};

export type RedirectTargetResponse = {
  target_path: string;
  status_code: 301;
};

export type WorkSearchResponse = {
  query: string;
  items: Array<HomeItem>;
  next_cursor: string | null;
};

export type PerformerSummary = {
  id: string;
  name: string;
  href: string;
  image_url: string | null;
  image: ResponsiveImage | null;
};

export type ImageRendition = {
  url: string;
  rendition: "w320" | "w640" | "w960";
  width: number;
  height: number;
  mime_type: "image/jpeg" | "image/png" | "image/webp";
};

export type ResponsiveImage = {
  url: string;
  rendition: "w320" | "w640" | "w960";
  width: number;
  height: number;
  mime_type: "image/jpeg" | "image/png" | "image/webp";
  renditions: Array<ImageRendition>;
};

export type WorkImage = {
  url: string;
  rendition: "w320" | "w640" | "w960";
  width: number;
  height: number;
  mime_type: "image/jpeg" | "image/png" | "image/webp";
  renditions: Array<ImageRendition>;
};

export type WorkDetailResponse = {
  id: string;
  code: string;
  title: string;
  title_original: string | null;
  release_date: string | null;
  studio_name: string;
  summary: string | null;
  performers: Array<PerformerSummary>;
  images: Array<WorkImage>;
  related_works: Array<HomeItem>;
};

export type PerformerDetailResponse = {
  id: string;
  name: string;
  name_original: string | null;
  romanized_name: string | null;
  aliases: Array<string>;
  activity_status: "active" | "retired" | "unknown";
  agency: string | null;
  birth_year: number | null;
  height_cm: number | null;
  measurements: string | null;
  debut_year: number | null;
  image_url: string | null;
  works: Array<HomeItem>;
  images: Array<WorkImage>;
};

export type StudioSummary = {
  id: string;
  name: string;
  href: string;
};

export type StudioListResponse = {
  items: Array<StudioSummary>;
  next_cursor: string | null;
};

export type StudioDetailResponse = {
  id: string;
  name: string;
  works: Array<HomeItem>;
};

export type MessageResponse = {
  message: string;
};

export type AuthCodeRequest = {
  email: string;
  turnstile_token: string;
};

export type SignupRequest = {
  email: string;
  code: string;
  password: string;
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type ReauthenticateRequest = {
  password: string;
};

export type PasswordResetRequest = {
  email: string;
  code: string;
  password: string;
};

export type CloseAccountRequest = {
  code: string;
  notice_version: "2026-08-07";
};

export type InvitationAcceptRequest = {
  email: string;
  code: string;
  password: string;
};

export type InvitationCreateRequest = {
  email: string;
  role: "admin" | "editor" | "user";
  reason: string;
};

export type RevokeInvitationRequest = {
  reason: string;
};

export type Invitation = {
  id: string;
  email: string;
  role: "admin" | "editor" | "user";
  status: "pending" | "accepted" | "revoked" | "expired";
  invited_by: string;
  inviter: string;
  sent_at: string;
  expires_at: string;
  consumed_at: string | null;
  created_at: string;
};

export type InvitationListResponse = {
  items: Array<Invitation>;
};

export type UserSummary = {
  id: string;
  email: string;
  role: "owner" | "admin" | "editor" | "user";
};

export type SessionResponse = {
  user: UserSummary;
};

export type PageViewRequest = {
  content_type: "work" | "performer" | "studio";
  content_id: string;
};

export type ItemListResponse = {
  items: Array<HomeItem>;
  next_cursor: string | null;
};

export type HistoryItem = {
  item: HomeItem;
  viewed_at: string;
};

export type HistoryResponse = {
  items: Array<HistoryItem>;
};

export type ClearHistoryResponse = {
  hidden_count: number;
};

export type FeedbackRequest = {
  content_type?: "work" | "performer" | "studio" | null;
  content_id?: string | null;
  feedback_type: "correction" | "source_suggestion" | "rights" | "other";
  message: string;
  evidence_url?: string | null;
};

export type FeedbackItem = {
  content_type: "work" | "performer" | "studio" | null;
  content_id: string | null;
  feedback_type: "correction" | "source_suggestion" | "rights" | "other";
  message: string;
  evidence_url: string | null;
  id: string;
  review_status: "pending" | "reviewing" | "accepted" | "rejected" | "closed";
  created_at: string;
};

export type FeedbackListResponse = {
  items: Array<FeedbackItem>;
};

export type AdminFeedbackItem = {
  content_type: "work" | "performer" | "studio" | null;
  content_id: string | null;
  feedback_type: "correction" | "source_suggestion" | "rights" | "other";
  message: string;
  evidence_url: string | null;
  id: string;
  review_status: "pending" | "reviewing" | "accepted" | "rejected" | "closed";
  created_at: string;
  submitter: string;
  reviewer: string | null;
  reviewed_at: string | null;
};

export type AdminFeedbackListResponse = {
  items: Array<AdminFeedbackItem>;
};

export type FeedbackReviewRequest = {
  status: "reviewing" | "accepted" | "rejected" | "closed";
  reason: string;
};

export type ReviewTask = {
  id: string;
  task_type: "new_entity" | "field_review" | "duplicate" | "conflict" | "media" | "rights" | "publication";
  entity_type: "work" | "performer" | "studio" | "media" | null;
  entity_id: string | null;
  priority: number;
  status: "pending" | "claimed" | "approved" | "rejected" | "cancelled";
  assignee_id: string | null;
  assignee: string | null;
  target_label: string;
  due_at: string | null;
  claimed_at: string | null;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
};

export type ReviewTaskListResponse = {
  items: Array<ReviewTask>;
};

export type ReviewDecisionRequest = {
  reason: string;
};

export type ReviewReassignmentRequest = {
  assignee_id: string;
  reason: string;
};

export type ConflictResolution = "keep_current" | "accept_candidate" | "mark_unknown" | "merge" | "reject";

export type ConflictReview = {
  id: string;
  review_task_id: string;
  entity_type: "work" | "performer" | "studio" | "media";
  entity_id: string;
  field_name: string;
  current_value: unknown;
  candidate_value: unknown;
  source_id: string | null;
  source_name: string | null;
  source_priority: number | null;
  resolution: ConflictResolution | null;
  resolved_by: string | null;
  resolved_at: string | null;
  created_at: string;
};

export type ConflictReviewListResponse = {
  items: Array<ConflictReview>;
};

export type ResolveConflictRequest = {
  resolution: ConflictResolution;
  reason: string;
};

export type CSVValidationIssue = {
  field: string;
  code: string;
  message: string;
};

export type WorkCSVRow = {
  row_number: number;
  code: string;
  title: string;
  title_original?: string;
  release_date?: string;
  studio_id?: string;
  performer_ids?: Array<string>;
  summary?: string;
  issues: Array<CSVValidationIssue>;
};

export type WorkCSVPreflightResponse = {
  rows: Array<WorkCSVRow>;
  file_issues: Array<CSVValidationIssue>;
  total_count: number;
  valid_count: number;
  invalid_count: number;
};

export type WorkImportBatchResponse = {
  id: string;
  status: "accepted";
  input_count: number;
  accepted_count: number;
  rejected_count: number;
  entity_ids: Array<string>;
  idempotent_replay: boolean;
  received_at: string;
  completed_at: string;
};

export type WorkImportBatchListResponse = {
  items: Array<WorkImportBatchResponse>;
};

export type CreateWorkRequest = {
  code: string;
  title: string;
  title_original?: string | null;
  release_date?: string | null;
  studio_id?: string | null;
  summary?: string | null;
  performer_ids?: Array<string>;
  sources: Array<SourceEvidenceInput>;
  reason: string;
};

export type CreatePerformerRequest = {
  display_name: string;
  name_original?: string | null;
  romanized_name?: string | null;
  aliases?: Array<string>;
  adult_status?: "unverified" | "verified" | "restricted";
  activity_status?: "active" | "retired" | "unknown";
  agency?: string | null;
  birth_year?: number | null;
  height_cm?: number | null;
  measurements?: string | null;
  debut_year?: number | null;
  sources: Array<SourceEvidenceInput>;
  reason: string;
};

export type CreateStudioRequest = {
  name: string;
  canonical_slug: string;
  sources: Array<SourceEvidenceInput>;
  reason: string;
};

export type CreateRevisionRequest = {
  entity_type: "work" | "performer" | "studio";
  payload: Record<string, unknown>;
  sources: Array<SourceEvidenceInput>;
  reason: string;
};

export type SourceEvidenceInput = {
  source_type: "web_page" | "search_result" | "official" | "other";
  source_url?: string | null;
  source_title?: string | null;
  checked_at: string;
};

export type PublishEntityRequest = {
  entity_type: "work" | "performer" | "studio";
  revision_id?: string;
  canonical_slug: string;
  reason: string;
};

export type HideEntityRequest = {
  entity_type: "work" | "performer" | "studio";
  reason: string;
};

export type OperationsEntity = {
  id: string;
  entity_type: "work" | "performer" | "studio";
  canonical_slug?: string;
  status: string;
  revision_id: string;
  revision_status: "draft" | "reviewing" | "approved" | "rejected";
  created_at: string;
};

export type CatalogEntity = {
  id: string;
  entity_type: "work" | "performer" | "studio";
  label: string;
  status: "draft" | "reviewing" | "approved" | "published" | "hidden" | "takedown" | "merged";
  canonical_slug: string | null;
  current_revision_id: string | null;
  updated_at: string;
};

export type CatalogEntityListResponse = {
  items: Array<CatalogEntity>;
};

export type MergeEntityRequest = {
  entity_type: "work" | "performer" | "studio";
  target_entity_id: string;
  reason: string;
};

export type EntityMerge = {
  id: string;
  entity_type: "work" | "performer" | "studio";
  source_entity_id: string;
  target_entity_id: string;
  source_path: string;
  target_path: string;
  merged_at: string;
};

export type ContentRevision = {
  id: string;
  entity_type: "work" | "performer" | "studio";
  entity_id: string;
  version: number;
  payload: Record<string, unknown>;
  status: "draft" | "reviewing" | "approved" | "rejected";
  author: string;
  reviewer: string | null;
  reason: string;
  created_at: string;
  reviewed_at: string | null;
  sources: Array<SourceEvidence>;
  is_current: boolean;
  canonical_slug: string | null;
};

export type SourceEvidence = {
  field_name: string;
  source_type: "web_page" | "search_result" | "official" | "other" | "manual_csv" | "legacy_record";
  source_url: string | null;
  source_title: string | null;
  checked_at: string;
  operator: string | null;
  confidence: number;
  rights_status: "needs_review" | "allowed" | "restricted" | "takedown";
};

export type ContentRevisionListResponse = {
  items: Array<ContentRevision>;
};

export type OperationsUser = {
  id: string;
  email: string;
  role: "owner" | "admin" | "editor" | "user";
  account_status: "pending" | "active" | "locked" | "suspended" | "closed";
  created_at: string;
  last_login_at: string | null;
};

export type OperationsUserListResponse = {
  items: Array<OperationsUser>;
};

export type EditorialRecommendation = {
  id: string;
  work_id: string;
  work_code: string;
  work_title: string;
  work_href: string | null;
  position: number;
  starts_at: string;
  ends_at: string | null;
  reason: string;
  status: "active" | "paused" | "removed";
  created_by: string;
  created_at: string;
  updated_at: string;
};

export type EditorialRecommendationListResponse = {
  items: Array<EditorialRecommendation>;
};

export type DiscoveryMixRule = {
  work_slots: number;
  performer_slots: number;
  repeat_window: number;
  enabled: boolean;
  updated_at: string;
};

export type DiscoveryMixRuleRequest = {
  work_slots: number;
  performer_slots: number;
  repeat_window: number;
  enabled: boolean;
  reason: string;
};

export type EditorialRecommendationRequest = {
  work_id: string;
  position: number;
  starts_at: string;
  ends_at: string | null;
  reason: string;
  change_reason: string;
  status: "active" | "paused";
};

export type RemoveEditorialRecommendationRequest = {
  reason: string;
};

export type OperationsSystemHealth = {
  status: "ok" | "degraded";
  schema_version: number;
  pending_review_tasks: number;
  reviewing_revisions: number;
  pending_outbox_events: number;
  failed_outbox_events: number;
  media_bytes: number;
  verified_backup_age_seconds: number | null;
  media_reconcile_age_seconds: number | null;
  media_reconcile_issues: number;
  failed_media_reconciles: number;
  media_inspection_age_seconds: number | null;
  media_publication_issues: number;
  default_image_failures: number;
  failed_media_inspections: number;
  search_requests_24h: number;
  search_zero_results_24h: number;
  checked_at: string;
};

export type AuditLog = {
  id: string;
  actor_type: "user" | "worker" | "system";
  actor_id: string | null;
  actor: string | null;
  action: string;
  object_type: string;
  object_id: string | null;
  reason: string | null;
  request_id: string;
  occurred_at: string;
};

export type AuditLogListResponse = {
  items: Array<AuditLog>;
  truncated: boolean;
};

export type MediaManifestObject = {
  rendition: "master" | "w320" | "w640" | "w960";
  storage_scope: "private" | "public";
  storage_key: string;
  backup_path: string;
  public_url: string | null;
  sha256: string;
  mime_type: "image/webp";
  width: number;
  height: number;
  byte_size: number;
};

export type MediaManifestRequest = {
  asset_id: string;
  entity_type: "work" | "performer";
  entity_id: string;
  asset_type: "work_image" | "performer_avatar";
  source_type: string;
  source_url?: string | null;
  checked_at: string;
  confidence: number;
  purpose: "cover" | "gallery" | "avatar";
  position: number;
  is_primary: boolean;
  reason: string;
  tool_version: "media-python/1";
  objects: Array<MediaManifestObject>;
};

export type MediaManifestResponse = {
  asset_id: string;
  entity_media_id: string;
  version: number;
  object_count: number;
  status: "published";
  created_at: string;
};

export type PrimaryMedia = {
  asset_id: string;
  entity_media_id: string;
  purpose: "cover" | "gallery" | "avatar";
};

export type PrimaryMediaStateResponse = {
  entity_type: "work" | "performer";
  entity_id: string;
  entity_status: "draft" | "reviewing" | "approved" | "published" | "hidden" | "takedown" | "merged";
  primary: PrimaryMedia | null;
};

export type ReplacePrimaryMediaRequest = {
  expected_asset_id: string;
  manifest: MediaManifestRequest;
};

export type ReplacePrimaryMediaResponse = {
  media: MediaManifestResponse;
  previous_asset_id: string;
  old_asset_retired: boolean;
  private_retained_until: string | null;
};

export type CreateTakedownRequest = {
  requester_reference: string;
  entity_type: "work" | "performer" | "studio" | "media";
  entity_id: string;
  evidence_reference?: string | null;
};

export type CompleteTakedownRequest = {
  result_summary: string;
};

export type TakedownRequest = {
  id: string;
  requester_reference: string;
  entity_type: "work" | "performer" | "studio" | "media";
  entity_id: string;
  evidence_reference: string | null;
  status: "received" | "validating" | "approved" | "rejected" | "completed";
  assigned_to: string | null;
  received_at: string;
  decided_at: string | null;
  completed_at: string | null;
  result_summary: string | null;
  updated_at: string;
};

export type TakedownListResponse = {
  items: Array<TakedownRequest>;
};
