from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = ROOT / "packages" / "api-contracts" / "openapi.yaml"
OUTPUT_PATH = ROOT / "packages" / "api-contracts" / "src" / "generated.ts"
IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


class TypeGenerator:
    def __init__(self, schemas: dict[str, Any]) -> None:
        self.schemas = schemas

    def render_document(self) -> str:
        lines = [
            "// Generated by scripts/generate_openapi_types.py from packages/api-contracts/openapi.yaml.",
            "// Do not edit this file by hand; update OpenAPI and regenerate it.",
            "",
        ]
        for name, schema in self.schemas.items():
            lines.append(f"export type {name} = {self.render_type(schema)};")
            lines.append("")
        return "\n".join(lines)

    def render_type(self, schema: Any, level: int = 0) -> str:
        if not isinstance(schema, dict) or not schema:
            return "unknown"
        if "$ref" in schema:
            return self.reference_name(schema["$ref"])
        if "const" in schema:
            return self.literal(schema["const"])
        if "enum" in schema:
            return " | ".join(dict.fromkeys(self.literal(value) for value in schema["enum"]))
        if "oneOf" in schema:
            return self.join_types(schema["oneOf"], " | ", level)
        if "anyOf" in schema:
            return self.join_types(schema["anyOf"], " | ", level)
        if "allOf" in schema:
            flattened = self.flatten_object(schema)
            if flattened is not None:
                properties, required = flattened
                return self.render_object(properties, required, level)
            return self.join_types(schema["allOf"], " & ", level)

        schema_type = schema.get("type")
        if isinstance(schema_type, list):
            variants = []
            for item_type in schema_type:
                variant = dict(schema)
                variant["type"] = item_type
                variants.append(variant)
            return self.join_types(variants, " | ", level)
        if schema_type == "null":
            return "null"
        if schema_type == "string":
            return "string"
        if schema_type in ("integer", "number"):
            return "number"
        if schema_type == "boolean":
            return "boolean"
        if schema_type == "array":
            return f"Array<{self.render_type(schema.get('items', {}), level)}>"
        if schema_type == "object" or "properties" in schema:
            properties = schema.get("properties", {})
            required = set(schema.get("required", []))
            if not properties:
                additional = schema.get("additionalProperties")
                if isinstance(additional, dict):
                    return f"Record<string, {self.render_type(additional, level)}>"
                if additional is False:
                    return "Record<string, never>"
                return "Record<string, unknown>"
            return self.render_object(properties, required, level)
        return "unknown"

    def flatten_object(self, schema: dict[str, Any], seen: frozenset[str] = frozenset()) -> tuple[dict[str, Any], set[str]] | None:
        if "$ref" in schema:
            name = self.reference_name(schema["$ref"])
            if name in seen or name not in self.schemas:
                return None
            return self.flatten_object(self.schemas[name], seen | {name})
        if "allOf" in schema:
            properties: dict[str, Any] = {}
            required: set[str] = set()
            for branch in schema["allOf"]:
                flattened = self.flatten_object(branch, seen)
                if flattened is None:
                    return None
                branch_properties, branch_required = flattened
                properties.update(branch_properties)
                required.update(branch_required)
            required.update(schema.get("required", []))
            properties.update(schema.get("properties", {}))
            return properties, required
        if schema.get("type") == "object" or "properties" in schema:
            return dict(schema.get("properties", {})), set(schema.get("required", []))
        return None

    def render_object(self, properties: dict[str, Any], required: set[str], level: int) -> str:
        indent = "  " * (level + 1)
        closing_indent = "  " * level
        lines = ["{"]
        for name, property_schema in properties.items():
            key = name if IDENTIFIER.fullmatch(name) else json.dumps(name, ensure_ascii=False)
            optional = "" if name in required else "?"
            rendered = self.render_type(property_schema, level + 1)
            rendered = rendered.replace("\n", "\n" + indent)
            lines.append(f"{indent}{key}{optional}: {rendered};")
        lines.append(f"{closing_indent}}}")
        return "\n".join(lines)

    def join_types(self, schemas: list[Any], separator: str, level: int) -> str:
        rendered = [self.render_type(schema, level) for schema in schemas]
        return separator.join(dict.fromkeys(rendered))

    @staticmethod
    def reference_name(reference: str) -> str:
        prefix = "#/components/schemas/"
        if not isinstance(reference, str) or not reference.startswith(prefix):
            raise ValueError(f"unsupported OpenAPI reference: {reference!r}")
        return reference.removeprefix(prefix)

    @staticmethod
    def literal(value: Any) -> str:
        if value is None:
            return "null"
        if value is True:
            return "true"
        if value is False:
            return "false"
        return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def generated_source(openapi_path: Path = OPENAPI_PATH) -> str:
    document = yaml.safe_load(openapi_path.read_text(encoding="utf-8"))
    schemas = document.get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict) or not schemas:
        raise ValueError("OpenAPI components.schemas must be a non-empty mapping")
    return TypeGenerator(schemas).render_document()


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate TypeScript types from Release A OpenAPI schemas")
    parser.add_argument("--check", action="store_true", help="fail when generated.ts differs from OpenAPI")
    arguments = parser.parse_args()
    expected = generated_source()
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
    if arguments.check:
        if current != expected:
            print("OpenAPI TypeScript types are stale; run: npm run generate:api-types")
            return 1
        print("OpenAPI TypeScript types are current")
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print(f"generated {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
